def printDefinitionK8s(definition:dict, manifest:dict, patch:dict)->None:
    print("=============BUG Definition=============")
    print(f'Bug ID\t\t\t\t: {definition['id']}')
    print(f'Bug reported Platform\t\t: {definition['platform']}')
    print(f'Affected Version\t\t: {definition['version']}')
    print(f'Affected Component Categorization\t: {definition['affected-categorization']}')
    print(f'Severity\t\t\t\t: {definition['severity']}')
    print("========================================")
    if (definition['resolved'] == "open"):
        print("Full patch of the bug has not been produced yet")
    else:
        print("Full patch of the bug has been produced")
    print(f'Follow the link for more information about the bug status: {definition['resolved']}')
    print("========================================")
    print("Detailed Description About the Bug")
    print("========================================")
    print(definition['description'])
    print("========================================")
    print("Expected behaviour")
    print(definition['expected-behaviour'])
    print("========================================")
    print("Manual bug reproduction step")
    print("========================================")
    print("Use the below manifest to create Kubernetes Resource:")
    print(manifest)
    print("========================================")
    print("Modify the manifest as below")
    print(patch)